### ISSUE TITLE
Fix to Usable

### ISSUE THREAD

**Issue by kayabaakihiko13** [fitriadyaa/RAG-api-embedchain#1]
Selamat Pagi kak @fitriadyaa 
Permisi kak @fitriadyaa izin bantu contrib kak,karena project kakak bagus tp bisakah saya merapikan ?

terima kasih

**Comment by kayabaakihiko13** [comment]
ini kak @fitriadyaa  mungkin bisa direview ulang kak
https://github.com/kayabaakihiko13/RAG-api-embedchain
terima kasih atas perhatiannya

**Comment by fitriadyaa** [comment]
Halo mas @kayabaakihiko13 terimakasih atas kontribusinya, jika berkenan mas bisa pull request yaa
